name: "Create PR custom action"
description: "Create a PR and a temporary branch, close duplicates"
inputs:
  files:
    description: "Files to add"
    required: true
  temp_branch_prefix:
    description: "Prefix for temporary git branch to be created, e.g, ci-docs"
    required: true
  pull_request_title:
    description: "Pull Request title to use"
    required: true
  github_token:
    description: "GitHub token for GitHub CLI"
    required: true
outputs:
  pull_request_id:
    description: "Pull request ID created"
    value: ${{ steps.create-pr.outputs.pr_id }}
  temp_branch:
    description: "Temporary branch created with staged changed"
    value: ${{ steps.create-pr.outputs.temp_branch }}
runs:
  using: "composite"
  steps:
    - id: adjust path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: test input format
      run: echo "${FILES}"
      env:
        FILES: ${{ inputs.files }}
      shell: bash
    - id: create-pr
      run: |
        echo "pull_request_id=10" >> $GITHUB_OUTPUT
        echo temp_branch="${TEMP_BRANCH_PREFIX}"-"${GITHUB_RUN_ID}" >> "$GITHUB_OUTPUT"
        echo $FILES
        gh config list
      env:
        FILES: ${{ inputs.files }}
        TEMP_BRANCH_PREFIX: ${{ inputs.temp_branch_prefix }}
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
