version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    ignore:
      # 2022-04-23: Ignoring boto3 changes until we need to care about them.
      - dependency-name: "boto3"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    allow:
      # Allow updates for AWS CDK
      - dependency-name: "aws-cdk"

#   - package-ecosystem: "pip"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     target-branch: "develop"
#     update_types:
#       - "semver:major"
#     labels:
#       - "do-not-merge"
#       - "dependencies"
#     commit-message:
#       prefix: chore
#       include: scope
