version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    ignore:
      # 2022-04-23: Ignoring boto3 changes until we need to care about them.
      - dependency-name: "boto3"
    groups:
      typing-dependencies:
        patterns:
          - "mypy-boto3-*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: chore
      include: scope
    allow:
      # Allow updates for AWS CDK
      - dependency-name: "aws-cdk"

  #   - package-ecosystem: "pip"
  #     directory: "/"
  #     schedule:
  #       interval: "daily"
  #     target-branch: "develop"
  #     update_types:
  #       - "semver:major"
  #     labels:
  #       - "do-not-merge"
  #       - "dependencies"
  #     commit-message:
  #       prefix: chore
  #       include: scope

  - package-ecosystem: pip
    directory: /benchmark/src/instrumented
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /benchmark/src/reference
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /examples/event_handler_graphql/src
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /layer/scripts/layer-balancer
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily
