site_name: Powertools for AWS Lambda (Python)
site_description: Powertools for AWS Lambda (Python)
site_author: Amazon Web Services
repo_url: https://github.com/aws-powertools/powertools-lambda-python
edit_uri: edit/develop/docs

nav:
  - Homepage: index.md
  - Changelog: changelog.md
  - Tutorial: tutorial/index.md
  - Roadmap: roadmap.md
  - API reference: api/" target="_blank
  - Upgrade guide: upgrade.md
  - We Made This (Community): we_made_this.md
  - Core utilities:
      - core/tracer.md
      - core/logger.md
      - core/metrics.md
      - Event Handler:
          - core/event_handler/api_gateway.md
          - core/event_handler/appsync.md
  - Utilities:
      - utilities/parameters.md
      - utilities/batch.md
      - utilities/typing.md
      - utilities/validation.md
      - utilities/data_classes.md
      - utilities/parser.md
      - utilities/idempotency.md
      - utilities/feature_flags.md
      - utilities/streaming.md
      - utilities/middleware_factory.md
      - utilities/jmespath_functions.md
      - CloudFormation Custom Resources: https://github.com/aws-cloudformation/custom-resource-helper" target="_blank

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  logo: media/aws-logo-light.svg
  favicon: media/aws-logo-light.svg
  custom_dir: docs/overrides

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
      restrict_base_path: false
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2022 Amazon Web Services

plugins:
  - git-revision-date
  - search

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/aws-amplify.min.js
  - javascript/extra.js

extra:
  version:
    provider: mike
    default: latest
