[tool.poetry]
name = "aws_lambda_powertools"
version = "2.16.0b2"
description = "AWS Lambda Powertools is a developer toolkit to implement Serverless best practices and increase developer velocity."
authors = ["Amazon Web Services"]
include = ["aws_lambda_powertools/py.typed", "THIRD-PARTY-LICENSES"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT No Attribution License (MIT-0)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
repository = "https://github.com/awslabs/aws-lambda-powertools-python"
documentation = "https://awslabs.github.io/aws-lambda-powertools-python/"
readme = "README.md"
keywords = ["aws_lambda_powertools", "aws", "tracing", "logging", "lambda", "powertools", "feature_flags", "idempotency", "middleware"]
# MIT-0 is not recognized as an existing license from poetry.
# By using `MIT` as a license value, a `License :: OSI Approved :: MIT License` classifier is added to the classifiers list.
license = "MIT"

[tool.poetry.urls]
"Issue tracker" = "https://github.com/awslabs/aws-lambda-powertools-python/issues"
"Releases" = "https://github.com/awslabs/aws-lambda-powertools-python/releases"

[tool.poetry.dependencies]
python = "^3.7.4"
aws-xray-sdk = { version = "^2.8.0", optional = true }
fastjsonschema = { version = "^2.14.5", optional = true }
pydantic = { version = "^1.8.2", optional = true }
boto3 = { version = "^1.20.32", optional = true }
typing-extensions = "^4.4.0"

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^7.2"}
pytest = "^7.3.1"
black = "^23.3"
boto3 = "^1.18"
flake8 = [
  # https://github.com/python/importlib_metadata/issues/406
  { version = "*", python="^3.7" },
  { version = ">=5", python= ">=3.8"},
]
flake8-builtins = "^2.1.0"
flake8-comprehensions = "^3.12.0"
flake8-debugger = "^4.0.0"
flake8-fixme = "^1.1.1"
flake8-variables-names = "^0.0.5"
flake8-black = "^0.3.6"
isort = "^5.11.5"
pytest-cov = "^4.0.0"
pytest-mock = "^3.5.1"
pdoc3 = "^0.10.0"
pytest-asyncio = "^0.21.0"
bandit = "^1.7.5"
radon = "^5.1.0"
xenon = "^0.9.0"
flake8-eradicate = "^1.2.1"
flake8-bugbear = "^23.3.12"
mkdocs-git-revision-date-plugin = "^0.3.2"
mike = "^1.1.2"
retry = "^0.9.2"
pytest-xdist = "^3.2.1"
aws-cdk-lib = "^2.75.0"
"aws-cdk.aws-apigatewayv2-alpha" = "^2.38.1-alpha.0"
"aws-cdk.aws-apigatewayv2-integrations-alpha" = "^2.38.1-alpha.0"
"aws-cdk.aws-apigatewayv2-authorizers-alpha" = "^2.38.1-alpha.0"
pytest-benchmark = "^4.0.0"
python-snappy = "^0.6.1"
mypy-boto3-appconfig = "^1.26.71"
mypy-boto3-cloudformation = "^1.26.108"
mypy-boto3-cloudwatch = "^1.26.127"
mypy-boto3-dynamodb = "^1.26.115"
mypy-boto3-lambda = "^1.26.122"
mypy-boto3-logs = "^1.26.53"
mypy-boto3-secretsmanager = "^1.26.135"
mypy-boto3-ssm = "^1.26.97"
mypy-boto3-s3 = "^1.26.127"
mypy-boto3-xray = "^1.26.122"
types-requests = "^2.30.0"
typing-extensions = "^4.4.0"
mkdocs-material = "^9.1.13"
filelock = "^3.12.0"
checksumdir = "^1.2.0"
mypy-boto3-appconfigdata = "^1.26.70"
importlib-metadata = "^6.6"
ijson = "^3.2.0"
typed-ast = { version = "^1.5.4", python = "< 3.8"}
hvac = "^1.1.0"
aws-requests-auth = "^0.4.3"

[tool.poetry.extras]
parser = ["pydantic"]
validation = ["fastjsonschema"]
tracer = ["aws-xray-sdk"]
all = ["pydantic", "aws-xray-sdk", "fastjsonschema"]
# allow customers to run code locally without emulators (SAM CLI, etc.)
aws-sdk = ["boto3"]

[tool.poetry.group.dev.dependencies]
cfn-lint = "0.77.4"
mypy = "^1.1.1"
types-python-dateutil = "^2.8.19.6"
httpx = ">=0.23.3,<0.25.0"

[tool.coverage.run]
source = ["aws_lambda_powertools"]
omit = ["tests/*", "aws_lambda_powertools/exceptions/*", "aws_lambda_powertools/utilities/parser/types.py", "aws_lambda_powertools/utilities/jmespath_utils/envelopes.py"]
branch = true

[tool.coverage.html]
directory = "test_report"
title = "Lambda Powertools Test Coverage"

[tool.coverage.report]
fail_under = 90
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Ignore runtime type checking
    "if TYPE_CHECKING:",

    # Ignore type function overload
    "@overload",
]

[tool.isort]
profile = "black" # resolves conflict with black
skip = "example"

[tool.black]
line-length = 120
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | example
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
testpaths = "./tests"
markers = [
    "perf: marks perf tests to be deselected (deselect with '-m \"not perf\"')",
]

[build-system]
requires = ["poetry-core>=1.3.2"]
build-backend = "poetry.core.masonry.api"

# poetry-core (PR #318) stopped generating setup.py by default, this enables it again.
[tool.poetry.build]
generate-setup-file = true

# NOTE
# As of now, Feb 2020, flake8 don't support pyproject
# For latest: https://github.com/flying-sheep/awesome-python-packaging
