blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aws-powertools/powertools-lambda-python/discussions/new
    about: Ask a general question about Lambda Powertools
