# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:

env:
  BRANCH: develop
  ORIGIN: heitorlessa/aws-lambda-powertools-python-test

jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: changelog-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git client setup and refresh tip
        run: |
          git config user.name "Release bot"
          git config user.email "aws-devax-open-source@amazon.com"
          git config pull.rebase true
          git config remote.origin.url >&-
          git pull origin "${BRANCH}"
      - name: "Generate latest changelog"
        run: make changelog
      - name: Update Changelog in trunk
        run: |
          HAS_CHANGE=$(git status --porcelain)
          test -z "${HAS_CHANGE}" && echo "Nothing to update" && exit 0
          git add CHANGELOG.md
          git commit -m "${COMMIT_MSG}"

          git pull origin "${BRANCH}" # prevents concurrent branch update failing push
          git checkout -b "${TEMP_BRANCH}"
          git push origin "${TEMP_BRANCH}"

          gh pr create --title "${PR_TITLE}" --body "${PR_BODY}: ${WORKFLOW_URL}" --base "${BRANCH}" --head "${TEMP_BRANCH}"
        env:
          COMMIT_MSG: "chore(ci): update changelog with latest changes"
          PR_TITLE: "chore(ci): changelog rebuild"
          PR_BODY: "This is an automated PR created from an automated workflow"
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEMP_BRANCH: "ci-changelog-${{ github.run_id}}"

  # changelog:
  #   uses: ./.github/workflows/reusable_publish_changelog.yml
