# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  BRANCH: develop
  ORIGIN: heitorlessa/aws-lambda-powertools-python-test


permissions:
  contents: read

jobs:
  changelog:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    concurrency:
      group: changelog-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Generate latest changelog"
        run: make changelog
      - name: Create PR
        id: create-pr
        uses: ./.github/actions/create-pr
        with:
          files: "CHANGELOG.md"
          temp_branch_prefix: "ci-changelog"
          pull_request_title: "chore(ci): changelog rebuild"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug output
        run: |
          echo "PR number: ${PR_ID}"
          echo "Branch: ${BRANCH}"
        env:
          PR_ID: ${{ steps.create-pr.outputs.pull_request_id}}
          BRANCH: ${{ steps.create-pr.outputs.temp_branch}}
  # changelog:
  #   uses: ./.github/workflows/reusable_publish_changelog.yml
