name: Docs

# PROCESS
#
# 1. Build User Guide and API docs
# 2. Publish to GitHub Pages
# 3. Publish to S3 (new home)

# USAGE
#
# Always triggered on PR merge when changes in documentation changes occur.

on:
  push:
    branches:
      - develop
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "examples/**"
      - "CHANGELOG.md"

permissions:
  contents: read

jobs:
  release-docs:
    permissions:
      contents: write  # push to gh-pages
      pages: write     # deploy gh-pages website
      id-token: write  # trade JWT token for AWS credentials in AWS Docs account
    secrets: inherit
    uses: ./.github/workflows/reusable_publish_docs.yml
    with:
      version: develop
      alias: stage