name: Code quality

on:
  pull_request:
    paths:
      - "aws_lambda_powertools/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
    branches:
      - develop
      - v2
  push:
    paths:
      - "aws_lambda_powertools/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
    branches:
      - develop
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      PYTHON: "${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: make dev
      - name: Formatting and Linting
        run: make lint
      - name: Static type checking
        run: make mypy
      - name: Test with pytest
        run: make test
      - name: Security baseline
        run: make security-baseline
      - name: Complexity baseline
        run: make complexity-baseline
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # 3.1.3
        with:
          file: ./coverage.xml
          env_vars: PYTHON
          name: aws-lambda-powertools-python-codecov
