name: Release Drafter

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
