name: Release Drafter

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@569eb7ee3a85817ab916c8f8ff03a5bd96c9c83e # v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
